### ISSUE TITLE
project dead or alive

### ISSUE THREAD

**Issue by ekaggrat** [yope/kamaq#2]
i just came accross this project via the reprap wiki .. it is very interesting to see a different way of doing things.  Is this project still under development or is it abandoned?

**Comment by yope** [comment]
Thanks for asking.
This project is neither under active development, nor abandoned right now. I have my 3D printer powered by this hardware and software printing successfully for a few years now with excellent results. If I find bugs I fix them. If I need new features I'll implement them as soon as I find the time and motivation to do so.
Right now my printer is still using the second prototype hardware and not the latest boards I designed that include all the electronics on a single PCB. I need to find some time to get it assembled and tested.
It would be cool to see someone else try this hardware/software. I'd be willing to help with getting it to work. I'd also happily accept bug-reports and feature-requests.

**Comment by ekaggrat** [comment]
ok great to hear that . I am still not clear as to how the steppers are run via the usb audio channels? and why instead of using the gpios directly

**Comment by yope** [comment]
Stepper motors need a square-wave signal to move in whole steps. For 3D printing, one mostly wants to move the motors in micro-stepping mode, which divides the steps into smaller "sub-steps", where the controlling voltage (coil current actually) is not only on or off, but has intermediate levels. The finer the sub-steps, the more the signal looks like a sine-wave. So in the end you are driving the motors with an analog signal instead of a square-wave. In the case of Kamaq, these signals are generated with an 8-channel audio codec, and amplified with a couple of class-D power amplifiers instead of regular stepper motor drivers. The stepper motors are connected to the audio amplifiers (instead of a regular speaker).
The reason for doing this is two-fold:
1. A Linux systems is usually not hard real-time capable, so controlling GPIO pins at high speed and with precise timing is a challenge to do. That's why other printers usually use a small microcontroller to do the real-time work. In the case of Kamaq, the audio codec (with its buffers) does the real-time work of generating the driving signals. Producing sound with Linux is trivial.
2. Near infinite micro-stepping, limited only by the mechanical non-linearity of the steppers and the resolution of the audio codec (16-bit), enabling very fine control of motion with very low audible noise (the motors move almost silently).

An extra benefit of the class D audio amplifiers is that they tend to be more efficient than stepper motor drivers, so they don't even get warm.
Why use Linux to run 3D printer firmware? Well, Linux systems are much more powerful than microcontrollers used typically for 3D printer control, so I can have the luxury of writing the printer firmware in a high-level programming language such as Python for example, and easily have things like an integrated web-interface, camera streaming, remote monitoring, etc... which traditional 3D printers only get when pairing them with a Raspberry-Pi. Well, Kamaq actually let's you run the whole printer from a Raspberry-Pi without needing a microcontroller to do the motor control ;)

**Comment by ekaggrat** [comment]
thanks ! that clears up a lot of things and seems to be a good approach. what hardware are you using it to run it currently? raspberry pi and discrete amplifiers?

**Comment by yope** [comment]
Right now, a custom i.MX6 based processor board with a raspberry-pi compatible GPIO connector. You can also use a Raspberry-Pi 3. The first prototype hardware (which my printer is still using) had separate PCB's for each stepper motor, containing 2 class-D mono audio amplifier IC's on each.
The new hardware version contains everything on one single PCB that has the format if a Pi-hat. It can be connected to a Raspberry-pi GPIO connector, but needs a separate USB connection to the USB port and an external power supply to provide 12V for steppers, hot-end and heated bed.
